### PR TITLE
[JENKINS-65868] Added remote IP in log entry for Audit Trail logs

### PR DESCRIPTION
**Pull request by chiefus**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] JENKINS-65868
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

In addition to username remote IP-address of a client is added to log entry of AuditTrail log.
Log output example

Justification:
There are cases when a potential Jenkins attacker can get access to a service account.
In this case this attacker can't be identified.
Information about a remote client IP-address may simplify an investigation process in future.

### CODE REVIEW

**Review by PierreBtz — CHANGES_REQUESTED** [review]
Thanks for the contribution! 

Note that the IP that you will get will not necessarily be the one of the client (see https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequest.html#getRemoteAddr--). For instance on my test instance I get the IP of my reverse proxy.

Given that it is not a regression (the same method was already used before) I'm happy to accept this as is if it's not an issue for your use case, however I would like to see a note somewhere on the readme about this gotcha. Can you please add something?

Thanks

**Comment by chiefus** [comment]
@PierreBtz, thanks for quick response.
Could you please clarify if you mean adding a description in the Readme file for this repository?
If yes, please clarify what section of this README file I can put it in.
+
Remote IP will be shown correctly if a reverse proxy is adding HTTP-header X-Forwarded-For with the original IP-address.

**Comment by PierreBtz** [comment]
@chiefus I was thinking adding something in the configuration part in the `README.md`, something like:

[IMPORTANT] 
.About the IP appearing in the logs
==== 
The plugin uses a method that cannot guarantee that the actual IP of the client is captured.
Be aware of this limitation, especially if your instance is configured behind a reverse proxy.

https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequest.html#getRemoteAddr--[More details]
====

**Comment by chiefus** [comment]
I've added a description to Readme. But it's not clear why tests are failed.
"[2021-06-15T08:12:27.332Z] Sending interrupt signal to process"

**Comment by PierreBtz** [comment]
> But it's not clear why tests are failed.

Technical error on jenkins.io, I pushed again

**Comment by chiefus** [comment]
`[2021-06-15T08:43:05.549Z] [ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.17:validate-hpi (default-validate-hpi) on project audit-trail: Dependency org.jenkins-ci.plugins:credentials:jar:2.3.18 requires Jenkins 2.222.4 or higher. -> [Help 1]
`
@PierreBtz , it looks like another plugin dependency error.

**Comment by PierreBtz** [comment]
@chiefus strange, jenkins.io decided to run using an older core than the one declared in the pom (`-Djenkins.version=2.190.3`) thus the issue.
Do not waste time on this, I'll need to have a look to understand the configuration issue, it's not related to your PR though.

**Comment by PierreBtz** [comment]
@chiefus 

Fixed the issue with #55, I won't ask you to rebase, I ran everything locally and I'm satisfied the change is good.

Thanks for the contribution!

**Comment by PierreBtz** [comment]
@chiefus I just noticed that the release of the plugin I did on June 15 (3.9) somehow failed. The release is ok github side but not ok on the Update Center side.
Really sorry for this delay, I'll make a new release asap so that you can get this improvement in an official release.

**Comment by PierreBtz** [comment]
I just performed a new release (3.10) and I can see the artifact on Jenkins side. It should take around 4 hours to be advised in the Jenkins update center.

**Pull request merged**
